
services:
    db1:
        image: postgres:15
        container_name: postgres_db1
        environment:
            POSTGRES_USER: user1
            POSTGRES_PASSWORD: pass1
            POSTGRES_DB: db1
        ports:
            - "5433:5432"  # External port 5433 maps to internal 5432

    db2:
        image: postgres:15
        container_name: postgres_db2
        environment:
            POSTGRES_USER: user2
            POSTGRES_PASSWORD: pass2
            POSTGRES_DB: db2
        ports:
            - "5434:5432"  # External port 5434 maps to internal 5432


    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
            - "9093:9093"
            - "9094:9094"
        expose:
            - "9094"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092,PLAINTEXT://host.docker.internal:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9094
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "service"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
    postgres_data: